---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: kandi
    name: postgres-pod
sepc:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: kandi
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
      ports:
        - containerPort: 5432
...

